apiVersion: v1
kind: Service
metadata:
  name: website-app
  namespace: default   # ðŸ‘ˆ REQUIRED
spec:
  selector:
    app: website-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
